import type { Metadata } from "next";
import { InfoPage } from "@/components/info-page";

export const metadata: Metadata = { title: "Privacy" };

export default function PrivacyPage() {
  return <InfoPage eyebrow="Privacy" title="A clear account of how this site works." intro="Last updated: September 27, 2026. This page describes the current SCNZOS SecureLab implementation and will be updated as tool functionality changes." sections={[
    { title: "Privacy at a glance", children: <p>The File Privacy Inspector and Screenshot Privacy Cleaner are designed to process files locally in the browser. They keep working files in browser memory during the current session and do not send file contents to an external inspection or OCR API. URL tracing uses a SecureLab server endpoint because browser code cannot reliably inspect arbitrary cross-origin redirect headers.</p> },
    { title: "Information we collect", children: <><p>The application does not intentionally collect names, email addresses, account details, usage analytics, or tool results. It has no account system, database, or analytics code. Your hosting provider or network may still create routine server or security logs as part of delivering any website; those logs are controlled by the deployment environment.</p><p>File contents are not sent to analytics services. The application does not place uploaded files, screenshots, or their contents in localStorage or URL parameters.</p></> },
    { title: "File Privacy Inspector", children: <><p>Supported JPEG/JPG, PNG, WebP, PDF, and DOCX files are inspected locally in the browser. Files are kept in browser memory during the current inspection session and are not uploaded to an external server for metadata inspection.</p><p>The current file-size limit is 100 MB. The inspector does not use localStorage, URL parameters, or database storage for uploaded files. HEIC/HEIF is currently unsupported. Metadata availability depends on the file and its format, so browser-side processing cannot guarantee that every possible metadata field will be detected.</p></> },
    { title: "Screenshot Privacy Cleaner", children: <><p>Supported PNG, JPEG/JPG, and WebP screenshots are processed locally in the browser. OCR currently uses Tesseract.js. Screenshots remain in browser memory during processing and are not uploaded to an external OCR API. The current file-size limit is 25 MB.</p><p>Detected findings are selected in the browser. Blur and solid redactions are drawn into a separate canvas, so the original uploaded image is not permanently modified. Cleaned images are generated locally and downloaded from the browser. Screenshot contents are not stored in a database, and no analytics service receives them.</p><p>OCR may miss text, especially when it is low-resolution, stylized, obscured, or difficult to read. Detection is conservative and does not guarantee detection of every secret or sensitive value.</p></> },
    { title: "URL Redirect Visualizer", children: <p>URLs submitted to the Trace URL action are sent to the SecureLab server endpoint for the duration of the trace. The endpoint validates HTTP and HTTPS URLs, checks destinations against internal and private network protections, follows a bounded number of redirects, and returns redirect metadata. It does not intentionally store submitted URLs or destination page content in a database. The tool does not claim to be completely client-side.</p> },
    { title: "Cookies and analytics", children: <p>SCNZOS SecureLab does not set cookies and does not use analytics, advertising pixels, session replay, or similar tracking in the current implementation. No analytics service receives uploaded file or screenshot contents.</p> },
    { title: "Third-party services", children: <p>The File Privacy Inspector does not use an external metadata API. The Screenshot Privacy Cleaner runs Tesseract.js in the browser instead of sending screenshots to an OCR service. Tesseract.js may retrieve the worker and language resources needed for OCR as software assets, depending on the browser and deployment; the screenshot data is not sent to an OCR API. The deployment platform may provide the infrastructure needed to serve the site.</p> },
    { title: "Data retention", children: <p>Files and screenshots are retained by the application only in browser memory during the current session. Removing them or leaving the page clears the application&apos;s current references. The generated cleaned image exists in browser memory until it is downloaded or the page is reset; the application does not permanently store it. There is no database storage for uploaded files, screenshots, URLs, or tool results.</p> },
    { title: "Security", children: <p>Uploaded files and OCR text are treated as untrusted data. The tools do not execute uploaded files or render uploaded HTML/SVG as page markup. Redaction is applied to the exported canvas pixels, while the original screenshot remains separate. These tools provide inspection and redaction assistance, not a guarantee that every privacy risk has been found.</p> },
    { title: "Browser limitations", children: <p>Browser-based processing depends on the user&apos;s browser, device memory, available processing power, supported image decoders, and network access needed for library resources such as OCR assets. Different files expose different metadata, and OCR quality varies with image clarity. A browser or device may fail to process a file even when its format is listed as supported.</p> },
    { title: "Changes to this policy", children: <p>When a tool gains new processing, or the site changes its analytics, cookies, third-party services, or data handling, this page will be updated with the relevant details and a new &ldquo;Last updated&rdquo; date.</p> },
    { title: "Contact", children: <p>This current deployment does not provide a contact form or a dedicated privacy email address. A deployment operator should publish a monitored privacy contact here before inviting privacy questions or enabling additional services.</p> },
  ]} />;
}
